### ISSUE TITLE
Desired State Configuration Error

### ISSUE THREAD

**Issue by baba-dude** [kkolk/mssql#1]
I am Getting one error as below.
PowerShell DSC resource MSFT_SqlSetup failed to execute Set-TargetResource functionality with error message:System.Exception: Test-TargetResource returned false after calling Set-TargetResource.

Can you Please advise where would be the mistake i did ?

Thank you

**Comment by hanssonsebastian** [comment]
Check the Summary.txt for errors during install, located here. 

Path for 2016 SQL
C:\Program Files\Microsoft SQL Server\130\Setup Bootstrap\Log.

Could be a pending reboot or a missing path or something like that :)
